import { Inter } from "next/font/google";
import "./globals.css";
import FCMWrapper from "@/utils/wrapper/FCMWrapper";
import {MessageProvider} from "@/utils/context/MessageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <MessageProvider>
      <FCMWrapper>{children}</FCMWrapper>
      </MessageProvider>
      </body>
      </html>
  );
}
